### ISSUE TITLE
memo

### ISSUE THREAD

**Issue by nanopoteto** [nanopoteto/B3_code#6]
# attr_mask = np.array([0, 1, 2, 3, 4, 6, 7, 10, 12, 13, 14, 16, 18, 19, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 33, 34, 35, 36, 37, 38])
    attr_mask = np.array([0, 1, 2, 3, 6, 7, 10, 12, 13, 14, 16, 18, 19, 25, 27, 28, 30,  34, 37, 38])

**Comment by nanopoteto** [comment]
attr_mask = np.array([0, 1, 2, 3, 6, 7, 10, 12, 13, 14, 16, 18, 19, 25, 27, 28, 30,  34, 37, 38])

**Comment by Wotipati** [comment]
help me!!!
